"""Governed Python support targets used by compatibility validation."""

DEFAULT_PYTHON_VERSION = "3.13"
PYTHON_COMPATIBILITY_VERSION = "3.14"
PYTHON_COMPATIBILITY_INTERPRETER = f"python{PYTHON_COMPATIBILITY_VERSION}"
SUPPORTED_PYTHON_REQUIREMENT = ">=3.13,<3.15"
