"""Governed Python support targets used by compatibility validation."""

DEFAULT_PYTHON_VERSION = "3.13"
PYTHON_COMPATIBILITY_VERSION = "3.14"
PYTHON_COMPATIBILITY_INTERPRETER = f"python{PYTHON_COMPATIBILITY_VERSION}"
_COMPATIBILITY_MAJOR, _COMPATIBILITY_MINOR = (
    int(part) for part in PYTHON_COMPATIBILITY_VERSION.split(".")
)
SUPPORTED_PYTHON_REQUIREMENT = (
    f">={DEFAULT_PYTHON_VERSION},<{_COMPATIBILITY_MAJOR}.{_COMPATIBILITY_MINOR + 1}"
)
