"""Update the autogenerated source line-count table in README.md."""

from __future__ import annotations

import argparse
import shutil
import subprocess
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
README_PATH = REPO_ROOT / "README.md"
START_MARKER = "<!-- CODEBASE_LINE_COUNT_TABLE:START -->"
END_MARKER = "<!-- CODEBASE_LINE_COUNT_TABLE:END -->"

LANGUAGE_EXTENSIONS: dict[str, tuple[str, ...]] = {
    "Python": (".py",),
    "TypeScript": (".ts", ".tsx"),
    "JavaScript": (".js", ".jsx"),
    "Shell": (".sh",),
    "HTML": (".html",),
    "Svelte": (".svelte",),
    "CSS": (".css", ".scss"),
    "JSON": (".json",),
    "Markdown": (".md", ".mdx"),
    "YAML": (".yml", ".yaml"),
    "TOML": (".toml",),
    "SQL": (".sql",),
    "Go": (".go",),
    "Java": (".java",),
    "Ruby": (".rb",),
    "PHP": (".php",),
    "C": (".c", ".h"),
    "C++": (".cc", ".cpp", ".cxx", ".hpp"),
    "C#": (".cs",),
}
EXTENSION_TO_LANGUAGE = {
    extension: language
    for language, extensions in LANGUAGE_EXTENSIONS.items()
    for extension in extensions
}


@dataclass
class LanguageStats:
    files: int = 0
    lines: int = 0


def _tracked_files() -> list[Path]:
    proc = subprocess.run(  # noqa: S603 — trusted input: git ls-files in a dev script
        [shutil.which("git") or "git", "ls-files"],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    files = []
    for line in proc.stdout.splitlines():
        if not line:
            continue
        path = REPO_ROOT / line
        if path.is_file():
            files.append(path)
    return files


def _count_lines(path: Path) -> int:
    with path.open("r", encoding="utf-8", errors="ignore") as fh:
        return sum(1 for _ in fh)


def build_table() -> str:
    stats: dict[str, LanguageStats] = defaultdict(LanguageStats)
    for path in _tracked_files():
        language = EXTENSION_TO_LANGUAGE.get(path.suffix.lower())
        if language is None:
            continue
        language_stats = stats[language]
        language_stats.files += 1
        language_stats.lines += _count_lines(path)

    ordered = sorted(
        ((language, data) for language, data in stats.items() if data.files > 0),
        key=lambda item: item[1].lines,
        reverse=True,
    )
    total_files = sum(item.files for _, item in ordered)
    total_lines = sum(item.lines for _, item in ordered)

    lines = [
        "## Codebase Line Count",
        "",
        "_This table is auto-updated by CI after successful builds on `main`._",
        "",
        "| Language | Files | Lines |",
        "| --- | ---: | ---: |",
    ]
    for language, data in ordered:
        lines.append(f"| {language} | {data.files:,} | {data.lines:,} |")
    lines.append(f"| **Total** | **{total_files:,}** | **{total_lines:,}** |")
    return "\n".join(lines)


def update_readme(readme_path: Path) -> bool:
    content = readme_path.read_text(encoding="utf-8")
    start_index = content.find(START_MARKER)
    end_index = content.find(END_MARKER)
    if start_index == -1 or end_index == -1 or end_index < start_index:
        raise ValueError(
            f"Missing markers in {readme_path}: {START_MARKER} / {END_MARKER}",
        )

    replacement = "\n".join(
        [
            START_MARKER,
            build_table(),
            END_MARKER,
        ],
    )
    end_marker_end = end_index + len(END_MARKER)
    updated = content[:start_index] + replacement + content[end_marker_end:]
    if updated == content:
        return False
    readme_path.write_text(updated, encoding="utf-8")
    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--readme",
        type=Path,
        default=README_PATH,
        help="Path to README file to update.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with status 1 if README needs to be updated.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    changed = update_readme(args.readme.resolve())
    if args.check and changed:
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover — tested via main() directly
    raise SystemExit(main())
